import {createError} from "h3";
import {WorkspaceFileBatchRequestSchema} from "nbook/shared/dto/workspace-file-operation.dto";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetMutation} from "nbook/server/workspace-files/project-open-guard";
import {requireReadyProjectByPublicId} from "nbook/server/workspace-files/project-session";
import {projectWorkspaceRef} from "nbook/server/workspace-files/project-identity";
import {batchWorkspacePathsTracked, USER_LOCAL_ACTOR} from "nbook/server/workspace-history/tracked-workspace-files";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
        tags: ["Workspace Files"],
        summary: "Batch copy or move workspace paths",
        requestBody: {
            content: {
                "application/json": {
                    schema: {
                        type: "object",
                        properties: {
                            kind: {type: "string", enum: ["copy", "move"]},
                            sources: {type: "array", minItems: 1, items: {type: "string"}},
                            destination: {type: "string", minLength: 1},
                            projectRoot: {type: "string"},
                            publicId: {type: "string"},
                            workspaceKind: {type: "string", enum: ["user-assets"]},
                        },
                        required: ["kind", "sources", "destination"],
                        additionalProperties: false,
                    },
                },
            },
        },
        responses: {200: {description: "逐项副作用结果；不保证原子事务"}, 400: {description: "Bad Request — validation failed"}},
    },
} as never);

export default defineEventHandler(async (event) => {
    const parsed = WorkspaceFileBatchRequestSchema.safeParse(await readBody(event));
    if (!parsed.success) {
        throw createError({statusCode: 400, message: parsed.error.issues[0]?.message ?? "批量文件请求不合法", data: {code: "INVALID_WORKSPACE_FILE_BATCH"}});
    }
    const body = parsed.data;
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    return withProjectTargetMutation(target, async (projectHandles) => {
        const assertBinding = body.projectRoot
            ? () => {
                const ready = requireReadyProjectByPublicId(projectWorkspaceRef(body.projectRoot), body.publicId);
                if (ready.workspace.root !== target.root) {
                    throw createError({statusCode: 409, message: "Project Workspace binding 已失效", data: {code: "PROJECT_BINDING_STALE"}});
                }
            }
            : undefined;
        assertBinding?.();
        return batchWorkspacePathsTracked({
            target,
            history: projectHandles?.history,
            kind: body.kind,
            sources: body.sources,
            destination: body.destination,
            actor: USER_LOCAL_ACTOR,
            assertBinding,
        });
    });
});
