import {createError} from "h3";
import {z} from "zod";
import {ProjectRootDtoSchema} from "nbook/shared/dto/project.dto";
import {resolveLlmlintSkillRoot, runLlmlintCheck, runLlmlintScan} from "nbook/server/workspace-files/llmlint-check";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetOperation} from "nbook/server/workspace-files/project-open-guard";
import {statWorkspacePath} from "nbook/server/workspace-files/workspace-files";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
        "tags": [
            "Workspace Files",
        ],
        "summary": "Run llmlint check on a workspace prose file (or recursively scan a directory)",
        "requestBody": {
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectRoot": {
                                "description": "Project Workspace root, single directory name under Workspace Root",
                                "type": "string",
                            },
                            "workspaceKind": {
                                "description": "Use the global user assets workspace",
                                "type": "string",
                                "enum": [
                                    "user-assets",
                                ],
                            },
                            "path": {
                                "type": "string",
                                "minLength": 1,
                                "description": "File path to scan",
                            },
                            "review": {
                                "type": "string",
                                "enum": ["agent", "human", "none", "all"],
                                "description": "Audience filter for lint hits",
                            },
                            "minLevel": {
                                "type": "string",
                                "enum": ["high", "medium", "low"],
                                "description": "Minimum severity to display",
                            },
                            "scanAll": {
                                "type": "boolean",
                                "description": "Disable Markdown masking (scan code blocks too)",
                            },
                        },
                        "required": [
                            "path",
                        ],
                        "additionalProperties": false,
                    },
                },
            },
        },
        "responses": {
            "200": {
                "description": "OK",
            },
            "400": {
                "description": "Bad Request — validation failed",
            },
            "502": {
                "description": "llmlint CLI failed to produce a report",
            },
            "503": {
                "description": "llmlint skill is not available in this runtime",
            },
        },
    } as never,
});

const LlmlintCheckBodySchema = z.object({
    projectRoot: ProjectRootDtoSchema.optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    review: z.enum(["agent", "human", "none", "all"]).optional().default("all"),
    minLevel: z.enum(["high", "medium", "low"]).optional().default("low"),
    scanAll: z.boolean().optional().default(false),
});

/**
 * 对指定章节/正文文件运行 llmlint `check`，返回结构化命中列表；
 * 目标是目录时（T0.4）递归扫描全部 .md/.markdown/.txt，返回聚合报告。
 *
 * 只读：绝不写回被扫描文件（llmlint 的 `check` 自身也永不改写正文）。
 * 通过 spawn CLI 调用，不 import llmlint 内部模块（它没有 exports 契约）。
 */
export default defineEventHandler(async (event) => {
    const body = LlmlintCheckBodySchema.parse(await readBody(event));
    const runtimePaths = runtimePathsFromEnv();
    const target = await resolveWorkspaceFileTarget(runtimePaths, body);
    return withProjectTargetOperation(target, async () => {
        const node = await statWorkspacePath(target.root, body.path);
        if (!node.isDirectory && !node.editable) {
            throw createError({statusCode: 400, message: "该文件不是可读写的文本文件，无法扫描"});
        }

        let skillRoot: string;
        try {
            skillRoot = await resolveLlmlintSkillRoot(runtimePaths);
        } catch (error) {
            throw createError({statusCode: 503, message: error instanceof Error ? error.message : String(error)});
        }

        try {
            if (node.isDirectory) {
                return await runLlmlintScan({
                    skillRoot,
                    absoluteDirPath: node.absolutePath,
                    review: body.review,
                    minLevel: body.minLevel,
                    scanAll: body.scanAll,
                });
            }
            return await runLlmlintCheck({
                skillRoot,
                absoluteFilePath: node.absolutePath,
                review: body.review,
                minLevel: body.minLevel,
                scanAll: body.scanAll,
            });
        } catch (error) {
            throw createError({statusCode: 502, message: error instanceof Error ? error.message : String(error)});
        }
    });
});
