import {z} from "zod";
import * as yaml from "yaml";
import {createError} from "h3";
import {ProjectRootDtoSchema} from "nbook/shared/dto/project.dto";
import {readWorkspaceTextFile, statWorkspacePath, type WorkspaceFileNode} from "nbook/server/workspace-files/workspace-files";
import {PROJECT_MANIFEST_FILE} from "nbook/server/workspace-files/project-manifest";
import {buildWorkspaceWriteConflict} from "nbook/server/workspace-files/workspace-file-conflict";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetMutation} from "nbook/server/workspace-files/project-open-guard";
import {USER_LOCAL_ACTOR, writeWorkspaceTextFileTracked} from "nbook/server/workspace-history/tracked-workspace-files";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import type {AbsoluteFsPath} from "nbook/server/runtime/paths/file-path";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Write content to a workspace file",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "File path"
                        },
                        "content": {
                            "type": "string",
                            "description": "File content"
                        }
                    },
                    "required": [
                        "path",
                        "content"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const WriteWorkspaceFileBodySchema = z.object({
    projectRoot: ProjectRootDtoSchema.optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    content: z.string(),
    baseContent: z.string().optional(),
    expectedMtimeMs: z.number().nullable().optional(),
    force: z.boolean().optional().default(false),
});

/**
 * 覆盖写入工作区文本文件。
 */
export default defineEventHandler(async (event) => {
    const body = WriteWorkspaceFileBodySchema.parse(await readBody(event));
    assertProjectManifestTitle(body.path, body.content);
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    return withProjectTargetMutation(target, async (projectHandles) => {
        // 冲突检测已读到的写前内容，直接作为记账 before 复用（省一次读盘）。
        let knownBefore: string | null | undefined = undefined;
        if (!body.force && body.expectedMtimeMs !== undefined) {
            const remoteState = await readRemoteState(target.root, body.path);
            knownBefore = remoteState.node === null ? null : remoteState.content;
            const actualMtimeMs = remoteState.node?.mtimeMs ?? null;
            if (actualMtimeMs !== body.expectedMtimeMs) {
                const conflict = await buildWorkspaceWriteConflict({
                    path: body.path,
                    expectedMtimeMs: body.expectedMtimeMs,
                    actualMtimeMs,
                    baseContent: body.baseContent ?? "",
                    localContent: body.content,
                    remoteContent: remoteState.content,
                    remoteExists: remoteState.node !== null,
                    node: remoteState.node,
                });
                throw createError({
                    statusCode: 409,
                    statusMessage: "Workspace file write conflict",
                    message: "真实文件已被修改，请先处理冲突",
                    data: conflict,
                });
            }
        }

        await writeWorkspaceTextFileTracked({target, history: projectHandles?.history, filePath: body.path, content: body.content, actor: USER_LOCAL_ACTOR, knownBefore});
        return statWorkspacePath(target.root, body.path);
    });
});

/**
 * BUG030 双保险：project.yaml 的 title 是书架身份源，清空保存会让书从列表消失
 * （列表侧已兜底显示目录名）。这里在保存源头拦截空 title，阻止坏 manifest 落盘。
 */
function assertProjectManifestTitle(filePath: string, content: string): void {
    if (filePath !== PROJECT_MANIFEST_FILE) {
        return;
    }
    let parsed: unknown;
    try {
        parsed = yaml.parse(content);
    } catch {
        return;
    }
    if (typeof parsed !== "object" || parsed === null || (parsed as {kind?: unknown}).kind !== "novel") {
        return;
    }
    const title = (parsed as {title?: unknown}).title;
    if (typeof title !== "string" || title.trim().length === 0) {
        throw createError({
            statusCode: 400,
            message: "project.yaml 的显示标题（title）不能为空——留空会让这本书从书架消失。请填写标题后再保存。",
        });
    }
}

/**
 * 读取当前真实文件状态；文件被外部删除时返回空内容和空节点。
 */
async function readRemoteState(root: AbsoluteFsPath, filePath: string): Promise<{
    node: WorkspaceFileNode | null;
    content: string;
}> {
    try {
        const [node, content] = await Promise.all([
            statWorkspacePath(root, filePath),
            readWorkspaceTextFile(root, filePath),
        ]);
        return {node, content};
    } catch (error) {
        if (typeof error === "object" && error !== null && "code" in error && (error as {code?: string}).code === "ENOENT") {
            return {
                node: null,
                content: "",
            };
        }
        throw error;
    }
}
